main: firewolf8385.elytrapvp.ElytraPvP
name: ElytraPVP
version: 1.0
description: A fun, new type of pvp
author: firewolf8385
softdepend: [PlaceholderAPI]
api-version: 1.15
load: POSTWORLD

commands:
  elytrapvp:
    usage: /<command>
    description: Main plugin command.
    aliases: [ep, epvp, elytra]
  stats:
    usage: /<command>
    description: View your stats.
  kits:
    usage: /<command>
    description: View kits.
  pay:
    usage: /<command>
    description: Pay another player coins.